require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FriendrequestsController do

  # This should return the minimal set of attributes required to create a valid
  # Friendrequest. As you add validations to Friendrequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "futurefriend" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FriendrequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all friendrequests as @friendrequests" do
      friendrequest = Friendrequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:friendrequests).should eq([friendrequest])
    end
  end

  describe "GET show" do
    it "assigns the requested friendrequest as @friendrequest" do
      friendrequest = Friendrequest.create! valid_attributes
      get :show, {:id => friendrequest.to_param}, valid_session
      assigns(:friendrequest).should eq(friendrequest)
    end
  end

  describe "GET new" do
    it "assigns a new friendrequest as @friendrequest" do
      get :new, {}, valid_session
      assigns(:friendrequest).should be_a_new(Friendrequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested friendrequest as @friendrequest" do
      friendrequest = Friendrequest.create! valid_attributes
      get :edit, {:id => friendrequest.to_param}, valid_session
      assigns(:friendrequest).should eq(friendrequest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Friendrequest" do
        expect {
          post :create, {:friendrequest => valid_attributes}, valid_session
        }.to change(Friendrequest, :count).by(1)
      end

      it "assigns a newly created friendrequest as @friendrequest" do
        post :create, {:friendrequest => valid_attributes}, valid_session
        assigns(:friendrequest).should be_a(Friendrequest)
        assigns(:friendrequest).should be_persisted
      end

      it "redirects to the created friendrequest" do
        post :create, {:friendrequest => valid_attributes}, valid_session
        response.should redirect_to(Friendrequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved friendrequest as @friendrequest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Friendrequest.any_instance.stub(:save).and_return(false)
        post :create, {:friendrequest => { "futurefriend" => "invalid value" }}, valid_session
        assigns(:friendrequest).should be_a_new(Friendrequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Friendrequest.any_instance.stub(:save).and_return(false)
        post :create, {:friendrequest => { "futurefriend" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested friendrequest" do
        friendrequest = Friendrequest.create! valid_attributes
        # Assuming there are no other friendrequests in the database, this
        # specifies that the Friendrequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Friendrequest.any_instance.should_receive(:update_attributes).with({ "futurefriend" => "MyString" })
        put :update, {:id => friendrequest.to_param, :friendrequest => { "futurefriend" => "MyString" }}, valid_session
      end

      it "assigns the requested friendrequest as @friendrequest" do
        friendrequest = Friendrequest.create! valid_attributes
        put :update, {:id => friendrequest.to_param, :friendrequest => valid_attributes}, valid_session
        assigns(:friendrequest).should eq(friendrequest)
      end

      it "redirects to the friendrequest" do
        friendrequest = Friendrequest.create! valid_attributes
        put :update, {:id => friendrequest.to_param, :friendrequest => valid_attributes}, valid_session
        response.should redirect_to(friendrequest)
      end
    end

    describe "with invalid params" do
      it "assigns the friendrequest as @friendrequest" do
        friendrequest = Friendrequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Friendrequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => friendrequest.to_param, :friendrequest => { "futurefriend" => "invalid value" }}, valid_session
        assigns(:friendrequest).should eq(friendrequest)
      end

      it "re-renders the 'edit' template" do
        friendrequest = Friendrequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Friendrequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => friendrequest.to_param, :friendrequest => { "futurefriend" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested friendrequest" do
      friendrequest = Friendrequest.create! valid_attributes
      expect {
        delete :destroy, {:id => friendrequest.to_param}, valid_session
      }.to change(Friendrequest, :count).by(-1)
    end

    it "redirects to the friendrequests list" do
      friendrequest = Friendrequest.create! valid_attributes
      delete :destroy, {:id => friendrequest.to_param}, valid_session
      response.should redirect_to(friendrequests_url)
    end
  end

end
